# - name: check the facts
#   hosts: all
#   connection: local
#   become: yes
#   tasks:
#   - name: install nginx if RedHat
#     ansible.builtin.dnf:
#      name: nginx
#      state: latest
#     when: ansible_os_family == "RedHat"

#   - name: install zip if RedHat
#     ansible.builtin.dnf:
#       name: zip
#       state: latest
#     when: ansible_os_family == "RedHat"


# - name: to check loops
#   hosts: local
#   connection: local
#   become: yes
#   tasks:
#   - name: check loops
#     ansible.builtin.debug:
#       msg: "apps are {{ item }}"
#     loop:
#       - nginx
#       - mysql
#       - redis


- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: installing packages
      ansible.builtin.package:
        name: "installing {{ item }}"
        state: latest
      loop:
        - nginx
        - mysql
        - zip

