- name: conditions
  hosts: all
  connection: local
  
  vars:
    number: 12

  tasks:
   - name: check if the number is greater than 10
     ansible.builtin.debug:
       msg: Given number: "{{ number }}" is less than 10
     when: number < 10 


