- name: data types
  hosts: localhost
  connection: local
  become: yes
  vars:
    course: "this is devops course"
    duration: 110 hours
    is_live: true
    tools:
      - linux
      - shell
      - ansible
    concepts:
      - cloud: aws 
        cm: ansible 
    tasks:
    - name: print all
      ansible.builtin.debug:
      msg: "course: {{ course }}, duration: {{ duration }}, is_love: {{ is_live }}, tools used: {{ tools }}, concepts covered: {{ concepts }}"
