- name: gather facts
  hosts: all
  connection: local

  tasks:
  - name: facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"


# returns the public IP address from ini file as well as from cmd
