- name:students data
  hosts: local
  connection: local
  -name: "Dillshad"
   dob: 04-07-2000
   addresses:
   -doorno: 21
    street: "gandhi nagar"
    type: "perm"
   -doorno: 22
    street: "gandhi nagar"
    type: "tem"
   -skills:
    -java
    -devops
    -cloud

   -name: "Dillshad"
    dob: 04-07-2000
    addresses:
    -doorno: 21
     street: "gandhi nagar"
     type: "perm"
    -doorno: 22
     street: "gandhi nagar"
     type: "tem"
  -skills:
   -java
   -devops
   -cloud

tasks:
 -name: print student info
  ansible.builtin.debug:
   student info:
   "name: {{ name }}"
   "dob: {{ dob }}"
   "skills: {{ skills }}

# ansible all -i "3.238.114.50", -e "ansible_user=ec2-user" -e "ansible_password=DevOps321" -m ping
 