- name: students data
  hosts: localhost
  connection: local

  vars:
   - name: "Dillshad"
     dob: 04-07-2000
     addresses:
     - doorno: 21
       street: "gandhi nagar"
       type: "perm"
     - doorno: 22
       street: "gandhi nagar"
       type: "tem"
     - skills:
       - java
       - devops
       - cloud

   - name: "Dillshad"
     dob: 04-07-2000
     addresses:
     - doorno: 21
       street: "gandhi nagar"
       type: "perm"
     - doorno: 22
       street: "gandhi nagar"
       type: "tem"
     - skills:
       - java
       - devops
       - cloud

  tasks:
    - name: Print each student's info
      ansible.builtin.debug:
        msg: |
          Name: {{ item.name }}
          DOB: {{ item.dob }}
          Skills: {{ item.skills }}
          Addresses:
          {% for addr in item.addresses %}
            - Door No: {{ addr.doorno }}, Street: {{ addr.street }}, Type: {{ addr.type }}
          {% endfor %}
      loop: "{{ students }}"


# ansible all -i "3.238.114.50", -e "ansible_user=ec2-user" -e "ansible_password=DevOps321" -m ping // to check conencted to ansible
#ansible all -i "3.238.114.50," -u ec2-user -e "ansible_password=DevOps321" -m setup  // to get fact file
#ansible-playbook -i "3.238.114.50," -e "ansible_user=ec2-user" -e "ansible_password=DevOps321" gatherfacts.yaml // to run a playbook
#var and msg are the only two variables which debug has 


 