# - name: play level variables
#   hosts: localhost
#   connection: local
#   vars:
#    course: ansible
#    Duration: 10hours
#    Learner: Dillshad

#   tasks:
#   - name: print course info
#     ansible.builtin.debug:
#       msg: "Course name is: {{ course }}, duration is: {{ Duration }}, learner is: {{ Learner }}"



# - name: play level variables
#   hosts: localhost
#   connection: local
#   vars:
#     course: ansible
#     duration: 11hours
#     learner: dillshad been learning since 8 months
  
#   tasks:
#     - name: print variables
#       ansible.builtin.debug:
#         msg: "course details are: {{ course }}, duration is {{ duration }}, learner is {{ learner }}"


- name: print file variables
  hosts: localhost
  connection: local
  vars_files:
    -course.yaml
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "course details are: {{ course }}, duration is {{ duration }}, learner is {{ learner }}"